### ISSUE TITLE
macos build `aarch64-linux-android` error

### ISSUE THREAD

**Issue by songjiachao** [aws/aws-lc-rs#635]
The following warnings were emitted during compilation:

warning: aws-lc-sys@0.23.1: Building with: CMake
warning: aws-lc-sys@0.23.1: Symbol Prefix: Some("aws_lc_0_23_1")
warning: aws-lc-sys@0.23.1: CMAKE environment variable set: cmake
warning: aws-lc-sys@0.23.1: Generating bindings - external bindgen. Platform: aarch64-linux-android

error: failed to run custom build command for `aws-lc-sys v0.23.1`

Caused by:
  process didn't exit successfully: `/Users/jiachaosong/Desktop/code/virtual-switch-hosts/src-tauri/target/debug/build/aws-lc-sys-9e07c7a465ee97aa/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREFIX
  cargo:rerun-if-env-changed=AWS_LC_SYS_PREGENERATING_BINDINGS
  cargo:rerun-if-env-changed=AWS_LC_SYS_EXTERNAL_BINDGEN
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_ASM
  cargo:rerun-if-env-changed=AWS_LC_SYS_CFLAGS
  cargo:rerun-if-env-changed=AWS_LC_SYS_PREBUILT_NASM
  cargo:rerun-if-env-changed=AWS_LC_SYS_C_STD
  cargo:rerun-if-env-changed=AWS_LC_SYS_CMAKE_BUILDER
  cargo:rerun-if-env-changed=AWS_LC_SYS_STATIC
  cargo:rerun-if-env-changed=CMAKE
  cargo:warning=Building with: CMake
  cargo:warning=Symbol Prefix: Some("aws_lc_0_23_1")
  cargo:rerun-if-env-changed=CMAKE
  cargo:warning=CMAKE environment variable set: cmake
  cargo:warning=Generating bindings - external bindgen. Platform: aarch64-linux-android
  cargo:rerun-if-env-changed=AWS_LC_SYS_INCLUDES

  --- stderr
  Failure invoking external bindgen! 

  bindgen-PARAMS: --prefix-link-name aws_lc_0_23_1_ --allowlist-file .*(/|\\)openssl((/|\\)[^/\\]+)+\.h --allowlist-file .*(/|\\)rust_wrapper\.h --rustified-enum point_conversion_form_t --default-macro-constant-type signed --with-derive-default --with-derive-partialeq --with-derive-eq --raw-line 
  // Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
  // SPDX-License-Identifier: Apache-2.0 OR ISC
   --generate functions,types,vars,methods,constructors,destructors /Users/jiachaosong/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.23.1/include/rust_wrapper.h --rust-target 1.59 --output /Users/jiachaosong/Desktop/code/virtual-switch-hosts/src-tauri/target/aarch64-linux-android/debug/build/aws-lc-sys-ba3c48b6983ff06f/out/bindings.rs --formatter rustfmt -- -I /Users/jiachaosong/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.23.1/include -I /Users/jiachaosong/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.23.1/aws-lc/include
  bindgen-STDOUT: 
  bindgen-STDERR: /Users/jiachaosong/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.23.1/aws-lc/include/openssl/base.h:61:10: fatal error: 'stdlib.h' file not found
  Unable to generate bindings: clang diagnosed error: /Users/jiachaosong/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.23.1/aws-lc/include/openssl/base.h:61:10: fatal error: 'stdlib.h' file not found

  thread 'main' panicked at /Users/jiachaosong/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.23.1/builder/main.rs:621:5:
  aws-lc-sys build failed. Please enable the 'bindgen' feature on aws-lc-rs or aws-lc-sys.For more information, see the aws-lc-rs User Guide: https://aws.github.io/aws-lc-rs/index.html
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
    Error `Failed to run `cargo build`: command ["cargo", "build", "--package", "virtual-switch-hosts", "--manifest-path", "/Users/jiachaosong/Desktop/code/virtual-switch-hosts/src-tauri/Cargo.toml", "--target", "aarch64-linux-android", "--lib"] exited with code 101

**Comment by justsmth** [comment]
Hello!

This error is occurring during the "bindings generation" process at the start of our build. (For several other targets we provide _pregenerated bindings_, but for `aarch64-linux-android` they are generated at build-time.) I often see this error when LLVM (or "libclang") is not available in the build environment. 

```
...
Unable to generate bindings: clang diagnosed error: /Users/jiachaosong/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.23.1/aws-lc/include/openssl/base.h:61:10: fatal error: 'stdlib.h' file not found
...
```

To fix this, you likely need to setup LLVM/libclang for your build environment. Our User Guide provides some guidance on [how to setup LLVM/libclang on macOS](https://aws.github.io/aws-lc-rs/requirements/apple.html#bindgen).  You might also check [the bindgen User Guide's instructions](https://rust-lang.github.io/rust-bindgen/requirements.html).

In this case, the solution might be as easy as the following command (if you use [Homebrew](https://brew.sh/)):
```
brew install clang
```

Let us know if these steps don't work for you.  We can take a deeper dive if needed.

**Comment by songjiachao** [comment]
❯ clang --version   

Homebrew clang version 19.1.6
Target: arm64-apple-darwin24.2.0
Thread model: posix
InstalledDir: /opt/homebrew/Cellar/llvm/19.1.6/bin
Configuration file: /opt/homebrew/etc/clang/arm64-apple-darwin24.cfg

**Comment by justsmth** [comment]
Hello! We just released [aws-lc-rs v1.12.1](https://github.com/aws/aws-lc-rs/releases/tag/v1.12.1) which provides pregenerated bindings for the `aarch64-linux-android` target. We believe this resolves the build problem described above.

Please let us know if you have any other build problems after upgrading. If needed, feel free to reopen this issue or create a new one. Thanks for helping to improve our library!

**Comment by ospfranco** [comment]
Hey! Thanks a lot to all of you folks for putting this library out there. I just faced this issue myself.

My `cargo.toml`:

```
[package]
name = "rn-aws-lc"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-lc-rs = { version = "1.12.1", features = ["fips", "bindgen"] }
```

I also added a `build.rs`:

```rust
use std::env;

fn main() {
    if env::var("CARGO_CFG_TARGET_OS").unwrap() == "android" {
        android();
    }
}

fn android() {
    println!("cargo:rustc-link-lib=c++_shared");
}
```

There is no direct `clang` dependency to be installed with brew:

```
Warning: No available formula with the name "clang". Did you mean clangql, cln, cling, clean, vlang, flang, clingo or clac?
==> Searching for similarly named formulae and casks...
==> Formulae
clang-build-analyzer            clang-uml                       cling                           clingo
clang-format ✔                  clangql                         clean                           clac
clang-format@11                 emacs-clang-complete-async      vlang
clang-format@8                  cln                             flang
```

But like above doing `clang --version` shows it has been installed through Xcode:

```
$ clang --version  
Apple clang version 16.0.0 (clang-1600.0.26.6)
Target: arm64-apple-darwin24.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Despite being on the latest version `1.12.1` it fails to compile. Any idea what could be the issue?

**Comment by justsmth** [comment]
Hello! I think the package you're looking for is "llvm". See the guidance here: https://aws.github.io/aws-lc-rs/requirements/apple.html#homebrew-1

**Comment by ospfranco** [comment]
Hi @justsmth. Thanks for the guidance but it doesn't work. I've installed the llvm via homebrew:

```
brew install llvm
```

According to the output it's not symlinked as it clashes with Xcode's provided clang. So I re-exported the binaries in the PATH:

```
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
```

I still get the same message.
